### ISSUE TITLE
Command list not showing when l is pressed

### ISSUE THREAD

**Issue by diveyez** [carlos8f/bot18#4]
It sits at this when I press l
---- PAID MEMBER ;) <3 ---
  startup   Press  l  to list available commands. +0ms
  startup  bot18/v0.4.31  ENGINE  ©  2018  Carlos Rodriguez  <carlos@s8f.org>  All rights reserved. +2ms
  startup  Fri, Jul 6, 2018 10:15 PM  +1ms
  startup Launched a webserver/GUI at http://127.0.0.1:8018 +0ms
  engine Selected gdax.btc-usd +0ms
  engine Selected gdax.eth-usd +0ms
  engine Selected gdax.ltc-usd +0ms
  engine Selected bitfinex2.btc-usdt +0ms
  engine Selected bitfinex2.ltc-usdt +0ms
  engine Selected bitfinex2.eth-usdt +0ms
  engine Done - Selected 6 market(s). +0ms

**Comment by tsrnc2** [comment]
Readme says thats all it does right now, output some text. Wait for updates.

**Comment by GarethWright** [comment]
Alpha is login only.
